apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: $GIT_REPO-hap
  namespace: NAMESPACE
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: $GIT_REPO
  minReplicas: $MIN_REPLICAS
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
