apiVersion: v1
kind: Service
metadata:
  name: $GIT_REPO
  namespace: NAMESPACE
  labels:
    app: $GIT_REPO
    service: $GIT_REPO
spec:
  selector:
    app: $GIT_REPO
  ports:
  - name: http
    protocol: TCP
    port: 3000
  - name: grpc
    protocol: TCP
    port: 9999
